version: "3.8"
services:
  portfolio:
    image: nginx:stable-alpine
    container_name: portfolio
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /home/ubuntu/docker-projects/tirthdadhaniya.me:/usr/share/nginx/html:ro
    networks:
      - npm-network
networks:
  npm-network:
    external: true