version: "3.8"
services:
  portfolio:
    build: .
    container_name: portfolio
    restart: always
    ports:
      - "8080:80"
    networks:
      - npm-network
networks:
  npm-network:
    external: true